my_string=input("Расскажи в двух словах как ты провел лето ")
print(len(my_string))
print (my_string.upper())
print (my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])